---
- name: download:cran
  cron:
    name: download:cran
    minute: "*/10"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:cran > /dev/null 2>&1

- name: projects:sync_pypi_deps
  cron:
    name: projects:sync_pypi_deps
    minute: "*/10"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production projects:sync_pypi_deps > /dev/null 2>&1

- name: update_source_ranks
  cron:
    name: update_source_ranks
    minute: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production projects:update_source_ranks > /dev/null 2>&1

- name: update_trending
  cron:
    name: update_trending
    minute: "6"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production github:update_trending > /dev/null 2>&1

- name: sync_permissions
  cron:
    name: sync_permissions
    minute: "12"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production users:sync_permissions > /dev/null 2>&1

- name: download:nuget
  cron:
    name: download:nuget
    minute: "18"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:nuget > /dev/null 2>&1

- name: github:sync_users
  cron:
    name: github:sync_users
    minute: "24"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production github:sync_users > /dev/null 2>&1

- name: github:sync_orgs
  cron:
    name: github:sync_orgs
    minute: "30"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production github:sync_orgs > /dev/null 2>&1

- name: github:sync_repos
  cron:
    name: github:sync_repos
    minute: "36"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production github:sync_repos > /dev/null 2>&1

- name: github:sync_issues
  cron:
    name: github:sync_issues
    minute: "42"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production github:sync_issues > /dev/null 2>&1

- name: bitbucket:find_new_repos
  cron:
    name: bitbucket:find_new_repos
    minute: "48"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production bitbucket:find_new_repos > /dev/null 2>&1

- name: gitlab:find_new_repos
  cron:
    name: gitlab:find_new_repos
    minute: "54"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production gitlab:find_new_repos > /dev/null 2>&1

- name: gitlab:find_updated_repos
  cron:
    name: gitlab:find_updated_repos
    minute: "0"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production gitlab:find_updated_repos > /dev/null 2>&1

- name: projects:potentially_outdated
  cron:
    name: projects:potentially_outdated
    minute: "0"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production projects:potentially_outdated > /dev/null 2>&1

- name: github:update_source_rank
  cron:
    name: github:update_source_rank
    minute: "0"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production github:update_source_rank > /dev/null 2>&1

- name: projects:sync
  cron:
    name: projects:sync
    minute: "30"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production projects:sync > /dev/null 2>&1

- name: download:bower_all
  cron:
    name: download:bower_all
    minute: "0"
    hour: "0"
    weekday: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:bower_all > /dev/null 2>&1

- name: projects:check_nuget_yanks
  cron:
    name: projects:check_nuget_yanks
    minute: "0"
    hour: "0"
    weekday: "2"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production projects:check_nuget_yanks > /dev/null 2>&1

- name: sitemap:refresh
  cron:
    name: sitemap:refresh
    minute: "0"
    hour: "0"
    weekday: "0"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production sitemap:refresh > /dev/null 2>&1

- name: projects:link_dependencies
  cron:
    name: projects:link_dependencies
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production projects:link_dependencies > /dev/null 2>&1

- name: projects:check_removed_status
  cron:
    name: projects:check_removed_status
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production projects:check_removed_status > /dev/null 2>&1

- name: download:bower
  cron:
    name: download:bower
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:bower > /dev/null 2>&1

- name: download:go
  cron:
    name: download:go
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:go > /dev/null 2>&1

- name: download:meteor
  cron:
    name: download:meteor
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:meteor > /dev/null 2>&1

- name: download:carthage
  cron:
    name: download:carthage
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:carthage > /dev/null 2>&1

- name: download:clojars
  cron:
    name: download:clojars
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:clojars > /dev/null 2>&1

- name: download:julia
  cron:
    name: download:julia
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:julia > /dev/null 2>&1

- name: download:alcatraz
  cron:
    name: download:alcatraz
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:alcatraz > /dev/null 2>&1

- name: download:dub
  cron:
    name: download:dub
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:dub > /dev/null 2>&1

- name: download:nimble
  cron:
    name: download:nimble
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:nimble > /dev/null 2>&1

- name: download:platformio
  cron:
    name: download:platformio
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:platformio > /dev/null 2>&1

- name: download:homebrew
  cron:
    name: download:homebrew
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:homebrew > /dev/null 2>&1

- name: download:wordpress
  cron:
    name: download:wordpress
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:wordpress > /dev/null 2>&1

- name: download:racket
  cron:
    name: download:racket
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:racket > /dev/null 2>&1

- name: download:small_registries
  cron:
    name: download:small_registries
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:small_registries > /dev/null 2>&1

- name: download:maven
  cron:
    name: download:maven
    minute: "1"
    hour: "1"
    job: cd /var/www/librariesio/current && /usr/local/bin/bundle exec rake RAILS_ENV=production download:maven > /dev/null 2>&1
