---
- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install sys Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items: "{{ sys_packages }}"

- name: Upgrade installed packages
  become: yes
  apt: upgrade=yes

- name: Configure the timezone
  become: yes
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  become: yes
  file: src=/usr/share/zoneinfo/{{timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Create deployment user
  user:
    name: deploy
    groups:
      - sudo

- name: Create deployment directories
  become: yes
  file:
    path: /var/www/
    state: directory
    owner: deploy
    group: deploy

- name: Install Bundler
  become: yes
  gem:
    name: bundler
    user_install: no
