---
- name: install java package
  apt: name={{item}} state=latest
  with_items:
    - openjdk-8-jdk
  become: yes

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository.
  apt_repository:
    repo: 'deb http://packages.elastic.co/elasticsearch/2.x/debian stable main'
    state: present
    update_cache: yes

- name: Install Elasticsearch.
  apt: pkg=elasticsearch state=present

- name: Copy Default File
  template: src=elasticsearch.j2 dest=/etc/default/elasticsearch mode=0644 force=yes
  notify: restart elasticsearch

- name: Copy config File
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml mode=0644 force=yes
  notify: restart elasticsearch

- name: Copy Systemd File for Instance
  template: src=systemd/elasticsearch.j2 dest=/usr/lib/systemd/system/elasticsearch.service mode=0644 force=yes
  notify:
  - reload systemd configuration
  - restart elasticsearch

- name: restart elasticsearch
  service: name=elasticsearch state=restarted enabled=yes

- name: install firewall
  apt: pkg=ufw state=latest

- name: Copy ufw config template
  template: src=ufw dest=/etc/default/ufw mode=0644 force=yes

- name: Copy ufw after.rules template
  template: src=after.rules dest=/etc/ufw/after.rules mode=0644 force=yes

- name: allow ssh
  ufw:
    rule: allow
    port: ssh

- name: allow elasticsearch tcp
  ufw:
    rule: allow
    port: 9300
    src: 10.0.0.0/8

- name: allow elasticsearch http
  ufw:
    rule: allow
    port: 9200
    src: 10.0.0.0/8

- name: disable firewall logging
  ufw:
    logging: "off"

- name: enable firewall
  ufw: state=disabled

- name: enable firewall
  ufw: state=enabled
