---
- name: reload systemd configuration
  command: systemctl daemon-reload

- name: Ensure elasticsearch is started
  service: name={{instance_init_script | basename}} state=started enabled=yes

- name: restart elasticsearch
  service: name=elasticsearch state=restarted enabled=yes
