---
- hosts: all
  vars:
    timezone: UTC
    sys_packages:
      - build-essential
      - libpq-dev
      - libxml2-dev
      - libxslt1-dev
      - nodejs
      - curl
      - git-core
      - software-properties-common
      - pgbouncer
      - docutils-common
      - cron
      - libcurl3
      - libcurl3-gnutls
      - libcurl4-openssl-dev
      - cmake
      - logrotate
      - libicu-dev
      - pkg-config
      - postgresql-client
  roles:
    - init
    - calebwoods.brightbox_ruby
    - cron
