---
- hosts: all
  vars_files:
    - vault.yml
  vars:
    timezone: UTC
    sys_packages:
      - curl
      - aptitude
      - logrotate
      - apt-transport-https
    logrotate_scripts:
      - name: elasticsearch
        path: "/usr/share/elasticsearch/log/*.log"
        options:
          - daily
          - rotate 100
          - size 50M
          - copytruncate
          - compress
          - delaycompress
          - missingok
          - notifempty
          - create 644 elasticsearch elasticsearch

  roles:
    - init
    - { role: elasticsearch, sudo: 'yes' }
    - { role: nickhammond.logrotate, sudo: 'yes' }
