
---
- hosts: all
  vars:
    timezone: UTC
    sys_packages:
      - curl
      - aptitude
      - logrotate
      - memcached
    logrotate_scripts:
      - name: memcached
        path: "/var/log/memcached.log"
        options:
          - rotate 30
          - daily
          - missingok
          - notifempty
          - compress
          - delaycompress
          - copytruncate
  roles:
    - init
    - { role: geerlingguy.memcached, memcached_memory_limit: 15000, memcached_listen_ip: "0.0.0.0", sudo: 'yes' }
    - { role: nickhammond.logrotate, sudo: 'yes'}
