---
- hosts: postgres
  vars_files:
    - vault.yml
  vars:
    timezone: UTC
    sys_packages:
      - aptitude
      - htop
    postgresql_version: 9.6
    postgresql_max_connections:      600
    postgresql_shared_buffers:       64GB
    postgresql_effective_cache_size: 192GB
    postgresql_work_mem:             33554kB
    postgresql_maintenance_work_mem: 2GB
    postgresql_max_wal_size:         8GB
    postgresql_min_wal_size:         4GB
    postgresql_checkpoint_completion_target: 0.9
    postgresql_wal_buffers:          16MB
    default_statistics_target:       500

    postgresql_database_extensions:
      - db: libraries_production
        extensions:
          - plpgsql
          - pg_stat_statements

    postgresql_databases:
      - name: libraries_production
        owner: libraries

    postgresql_users:
      - name: libraries
        pass: "{{ vault_postgres_libraries_password }}"
      - name: replicator
        pass: "{{ vault_postgres_replicator_password }}"

    postgresql_user_privileges:
      - name: libraries
        db: libraries_production
      - name: replicator
        role_attr_flags: 'REPLICATION,LOGIN'

    postgresql_pg_hba_default:
      - { type: local, database: all, user: '{{ postgresql_admin_user }}', address: '', method: '{{ postgresql_default_auth_method }}', comment: '' }
      - { type: local, database: all, user: all, address: '',             method: '{{ postgresql_default_auth_method }}', comment: '"local" is for Unix domain socket connections only' }
      - { type: host,  database: all, user: all, address: '127.0.0.1/32', method: '{{ postgresql_default_auth_method }}', comment: 'IPv4 local connections:' }
      - { type: host,  database: all, user: all, address: '::1/128',      method: '{{ postgresql_default_auth_method }}', comment: 'IPv6 local connections:' }
      - { type: host,  database: all, user: all, address: '0.0.0.0/0',    method: 'md5', comment: 'anyone with password' }
      - { type: host,  database: replication, user: replicator, address: '{{hostvars.replica.ansible_ssh_host}}/32', method: 'md5', comment: 'replica' }

    postgresql_listen_addresses:
      - '*'

    postgresql_wal_level: replica
    postgresql_max_wal_senders: 5
    postgresql_wal_keep_segments: 32

    postgresql_shared_preload_libraries:
      - pg_stat_statements

  roles:
    - init
    - ANXS.postgresql
